### ISSUE TITLE
grunt serve执行报错

### ISSUE THREAD

**Issue by kuangshengyu** [waylau/easyui-scaffold#1]
grunt serve执行报错

**Comment by waylau** [comment]
@kuangshengyu   错误信息贴下

**Comment by cherishYX** [comment]
确实有楼上说的这个问题,执行grunt serve报错
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'time-grunt'
Warning: Task "serve" not found. Use --force to continue.

加上force也是一样 . load**那个组件也安装了同样报错

**Comment by cherishYX** [comment]
> 确实有楼上说的这个问题,执行grunt serve报错
> Loading "Gruntfile.js" tasks...ERROR
> 
> > > Error: Cannot find module 'time-grunt'
> > > Warning: Task "serve" not found. Use --force to continue.
> 
> 加上force也是一样 . load**那个组件也安装了同样报错

已经解决  ,   重新安装报错插件  npm install --save-dev time-grunt  即可
